services:
  api:
    build: ./backend
    container_name: detectoclassif_back
    volumes:
      - ./backend:/app
      - ./data/tmp:/tmp/jobs
    environment:
      - HF_TOKEN=${HF_TOKEN:-}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  web:
    build: ./ui
    container_name: detectoclassif_front
    ports:
      - 3000:80 
    depends_on:
      - api